### ISSUE TITLE
issue #88 CodeClimae fix

### ISSUE THREAD

**Issue by gessfred** [geofot96/StudyBuddy#103]

**Comment by YBouquet** [comment]
if you add those lines:
```
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
```
in .travis.yml, you'll see:

> The test coverage on the diff in this pull request is ***.*% (**% is the threshold).

> This pull request will bring the total coverage in the repository to **.*%.

in the pull-request's codeclimate report

**Comment by YBouquet** [comment]
Now there is the test coverage on master 
However, since then, Travis doesn't run automatically anymore.
