### ISSUE TITLE
Search how local storage of files in a device works (SQL Lite)

### ISSUE THREAD

**Issue by geofot96** [geofot96/StudyBuddy#6]

**Comment by Arbaba** [comment]
Android Documentation suggests to use Room Persistence Library when dealing with SQL Lite. The purpose of this library is to avoid writing redundant and low level code when accessing information in the database. 

I went through this [tutorial ](https://codelabs.developers.google.com/codelabs/android-room-with-a-view/#7) and [Google's documentation](https://developer.android.com/training/data-storage/room/).

As explained in the [tutorial](https://codelabs.developers.google.com/codelabs/android-room-with-a-view/#7), it is good practice to create a Repository class when we have multiple data sources in a project. The idea is to encapsulate all data accesses with public methods in this class. This allows to abstract the interaction with the different data sources and provide a clean data API.
