### ISSUE TITLE
Connect with Firebase

### ISSUE THREAD

**Issue by Arbaba** [geofot96/StudyBuddy#86]
![image](https://user-images.githubusercontent.com/25588945/46724608-ab7d6b80-cc7a-11e8-91ae-24462cfa5e46.png)

**Comment by gessfred** [comment]
Serialization https://www.learnhowtoprogram.com/android/data-persistence/firebase-writing-pojos

**Comment by gessfred** [comment]
Mocking DataSnapshot inspiration https://github.com/FrangSierra/RxFirebase/blob/master/app/src/test/java/durdinapps/rxfirebase2/RxFirebaseDatabaseTest.java
